## A. Create a two dimensional array called arr9 with the following elements: [101, 322, 768], [233, 124, 390], [534, 122, 216]. From arr9, create an array called arr10 which contains the elements 101, 322, 390, 122 using advanced integer indexing. Create another array called arr11 which contains elements of first and second rows, and second and third columns using slicing operations.

In [2]:
import numpy as np

# Create the two-dimensional array arr9
arr9 = np.array([[101, 322, 768],
                 [233, 124, 390],
                 [534, 122, 216]])

# Create arr10 using advanced integer indexing
arr10 = arr9[[0, 0, 1, 2], [0, 1, 2, 1]]

# Create arr11 using slicing operations
arr11 = arr9[:2, 1:3]

# Display arr9, arr10, and arr11
print("arr9:")
print(arr9)
print("\narr10:")
print(arr10)
print("\narr11:")
print(arr11)


arr9:
[[101 322 768]
 [233 124 390]
 [534 122 216]]

arr10:
[101 322 390 122]

arr11:
[[322 768]
 [124 390]]


## B. Implement multiple linear regression and logistic regression on diabetes dataset. Write down your observations regarding the differences between these two algorithms.

In [3]:
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score

# Load the diabetes dataset
diabetes_data = load_diabetes()
X = diabetes_data.data
y = diabetes_data.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Multiple Linear Regression
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)
y_pred_linear = linear_reg.predict(X_test)
mse_linear = mean_squared_error(y_test, y_pred_linear)

# Logistic Regression
logistic_reg = LogisticRegression()
logistic_reg.fit(X_train, y_train)
y_pred_logistic = logistic_reg.predict(X_test)
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)

# Observations
print("Observations:")
print("Multiple Linear Regression - Mean Squared Error:", mse_linear)
print("Logistic Regression - Accuracy:", accuracy_logistic)


Observations:
Multiple Linear Regression - Mean Squared Error: 2900.193628493482
Logistic Regression - Accuracy: 0.0


In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score

# Load the diabetes dataset from a .csv file
diabetes_data = pd.read_csv('diabetes.csv')

# Split the dataset into features (X) and target variable (y)
X = diabetes_data.drop('Outcome', axis=1)
y = diabetes_data['Outcome']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Multiple Linear Regression
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)
y_pred_linear = linear_reg.predict(X_test)
mse_linear = mean_squared_error(y_test, y_pred_linear)

# Logistic Regression
logistic_reg = LogisticRegression()
logistic_reg.fit(X_train, y_train)
y_pred_logistic = logistic_reg.predict(X_test)
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)

# Observations
print("Observations:")
print("Multiple Linear Regression - Mean Squared Error:", mse_linear)
print("Logistic Regression - Accuracy:", accuracy_logistic)


Observations:
Multiple Linear Regression - Mean Squared Error: 0.17104527280850104
Logistic Regression - Accuracy: 0.7467532467532467


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
